### ISSUE TITLE
Logging non-string messages leads to AttributeError

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#1408]
Test code:

```
dut._log.info(dut.empty.value)
# dut.empty is a signal in the DUT, .value gets its BinaryValue object
```

This worked fine in older versions of cocotb, haven't attempted to find exact regression range yet. Now I get this trace:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/log.py", line 201, in format
    msg = '\n'.join([SimColourLogFormatter.loglevel2colour[record.levelno] % line for line in msg.split('\n')])
AttributeError: 'BinaryValue' object has no attribute 'split'
Call stack:
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/scheduler.py", line 355, in react
    self._event_loop(trigger)
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/scheduler.py", line 448, in _event_loop
    self.schedule(coro, trigger=trigger)
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/scheduler.py", line 758, in schedule
    result = coroutine._advance(send_outcome)
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/decorators.py", line 264, in _advance
    return super(RunningTest, self)._advance(outcome)
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/decorators.py", line 146, in _advance
    return outcome.send(self._coro)
  File "/home/philipp/.local/lib/python3.7/site-packages/cocotb/outcomes.py", line 38, in send
    return gen.send(self.value)
  File "path/to/test_fifo.py", line 45, in test_fifo_manual
    dut._log.info(dut.empty.value)
```

I'll try to come up with a test and a fix soon-ish.

**Comment by eric-wieser** [comment]
Correct fix to me looks to be to call `str(msg)` before splitting, which is essentially what the default builtin formatter does (strictly that does `'stuff %s stuff' % msg`, but that's equivalent).
