### ISSUE TITLE
asyncio-like debug for cocotb forks

### ISSUE THREAD

**Issue by toddstrader** [cocotb/cocotb#1458]
As discussed in #1435, native coroutines (`async def`) make debugging exceptions easier than generators decorated as cocotb coroutines.  However, `cocotb.fork()` gets you back into the difficult-to-debug state.  As @eric-wieser suggested, it would be handy if cocotb had an option to debug its forked coroutines [like asyncio Futures have](https://docs.python.org/3.6/library/asyncio-dev.html#asyncio-debug-mode).

As an example, I'm raising an exception in the `write_address_0` test of the axi_lite_slave example.  See:
https://github.com/toddstrader/cocotb/tree/async-coro-debug

Doing so results in:
```
   110.00ns ERROR    cocotb.regression                         regression.py:396  in _score_test                     Test Failed: write_address_0 (result was TypeError)
                                                                                                                     Traceback (most recent call last):
                                                                                                                       File "cocotb/examples/axi_lite_slave/tests/test_axi_lite_slave.py", line 45, in write_address_0
                                                                                                                         await axim.write(ADDRESS, DATA)
                                                                                                                       File "cocotb/cocotb/drivers/amba.py", line 143, in write
                                                                                                                         await c_addr.join()
                                                                                                                       File "cocotb/cocotb/triggers.py", line 127, in __await__
                                                                                                                         return (yield self)
                                                                                                                       File "cocotb/cocotb/drivers/amba.py", line 85, in _send_write_address
                                                                                                                         raise TypeError
                                                                                                                     TypeError
```

Which points me to line 143 of amba.py where the forked coro is being joined, and does not mention line 136 where the coro is being created.

As linked to above, asyncio handles this kind of debug by enabling some additional debugging in the event loop:

```python
#!/usr/bin/python3.6

import asyncio
import logging

async def thing(future, name, val):
    for i in range(val):
        print("{}: {}".format(name, i))
        if i == 1:
            #import pdb; pdb.set_trace()
            raise TypeError
        await asyncio.sleep(1)


loop = asyncio.get_event_loop()
loop.set_debug(True)                           # run-time debug enabled here
logging.basicConfig(level=logging.DEBUG)       # and here

futures = []
for x in range(1, 4):
    name = chr(ord('A') + x)
    future = asyncio.Future()
    futures.append(asyncio.ensure_future(thing(future, name, x)))

for f in futures:
    loop.run_until_complete(f)

loop.close()
```

Produces:

```
Traceback (most recent call last):
  File "./quxx.py", line 26, in <module>
    loop.run_until_complete(f)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "./quxx.py", line 11, in thing
    raise TypeError
TypeError
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<thing() done, defined at ./quxx.py:6> exception=TypeError() created at ./quxx.py:23>
source_traceback: Object created at (most recent call last):
  File "./quxx.py", line 23, in <module>
    futures.append(asyncio.ensure_future(thing(future, name, x)))
Traceback (most recent call last):
  File "./quxx.py", line 11, in thing
    raise TypeError
TypeError
```

This shows me the call stack into the event loop, but it also tells me where the Future was created (line 23).  This doesn't appear to do anything for pdb (it only sees the call stack into the event loop), but it's far better than nothing.

Is it possible to do something similar for cocotb forks?

**Comment by ktbarrett** [comment]
This occurs in asyncio because the `Tasks` you created in the loop had errored and the futures were not retrieved after the first of the `Tasks` threw an exception, causing the script to end. 

This is not possible right now.
1. If a `fork` gets an `Exception` it fails the test, `fork` is not a `Future` (some discussion on this in #922)
2. Reference cycles are causing `__del__` on `RunningTask`s to not be run (or at least historically there has been this issue).
