### ISSUE TITLE
Breathe needs pinning in CI

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1603]
https://readthedocs.org/projects/cocotb/builds/10787038/

Since we have Sphinx pinned to <3.0.0, we need to pin breathe too:
```
 Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/sphinx/cmd/build.py", line 275, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/sphinx/application.py", line 245, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/sphinx/application.py", line 397, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/sphinx/registry.py", line 465, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/breathe/__init__.py", line 13, in setup
    from . import directives
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/breathe/directives.py", line 4, in <module>
    from .renderer import DoxygenToRstRendererFactory
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/breathe/renderer/__init__.py", line 5, in <module>
    from . import sphinxrenderer
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 74, in <module>
    class DomainDirectiveFactory(object):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 90, in DomainDirectiveFactory
    'define': (c.CMacroObject, 'macro'),
AttributeError: module 'sphinx.domains.c' has no attribute 'CMacroObject'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/cocotb/envs/1592/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 90, in DomainDirectiveFactory
    'define': (c.CMacroObject, 'macro'),
AttributeError: module 'sphinx.domains.c' has no attribute 'CMacroObject'
The full traceback has been saved in /tmp/sphinx-err-r42dotmq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

**Comment by eric-wieser** [comment]
From the build logs:

ERROR: breathe 4.15.0 has requirement Sphinx>=3.0, but you'll have sphinx 2.4.4 which is incompatible.

**Comment by eric-wieser** [comment]
Note that the caching of the RTD PR builds is going to bite us here for a few days
