### ISSUE TITLE
Riviera-Pro fails issue_1279.test_sim_failure_a

### ISSUE THREAD

**Issue by themperek** [cocotb/cocotb#1870]
```
2020-05-26T17:36:56.0408534Z # COUT:      -.--ns INFO     cocotb.gpi                         ..mbed/gpi_embed.cpp:245  in embed_sim_init                  Python interpreter initialized and cocotb loaded!
2020-05-26T17:36:56.0505500Z # COUT:      0.00ns INFO     cocotb                                      __init__.py:189  in _initialise_testbench           Running on Riviera-PRO version 2019.10.138.7537
2020-05-26T17:36:56.0619821Z # COUT:      0.00ns INFO     cocotb                                      __init__.py:196  in _initialise_testbench           Running tests with cocotb v1.4.0.dev0 from /home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb
2020-05-26T17:36:56.0730520Z # COUT:      0.00ns INFO     cocotb                                      __init__.py:216  in _initialise_testbench           Seeding Python random module with 1590514616
2020-05-26T17:36:56.0828629Z # COUT:      0.00ns INFO     cocotb.regression                         regression.py:124  in __init__                        Found test issue_1279.test_sim_failure_a
2020-05-26T17:36:56.0924888Z # COUT:      0.00ns INFO     cocotb.regression                         regression.py:124  in __init__                        Found test issue_1279.test_sim_failure_b
2020-05-26T17:36:56.1018906Z # COUT:      0.00ns INFO     cocotb.regression                         regression.py:450  in _start_test                     Running test 1/2: test_sim_failure_a
2020-05-26T17:36:56.1103757Z # COUT:      0.00ns INFO     ..test_sim_failure_a.0x7fb82503ecc0       decorators.py:256  in _advance                        Starting test: "test_sim_failure_a"
2020-05-26T17:36:56.1267370Z # COUT:                                                                                                                      Description: None
2020-05-26T17:36:56.4533947Z # KERNEL: Simulation has finished. There are no more test vectors to simulate.
2020-05-26T17:36:56.4554018Z endsim
2020-05-26T17:36:56.4965248Z # COUT:      0.00ns ERROR    cocotb.scheduler                            __init__.py:256  in _sim_event                      Failing test at simulator request before test run completion: Simulator shutdown prematurely
2020-05-26T17:36:56.5092236Z # COUT: Traceback (most recent call last):
2020-05-26T17:36:56.5115254Z # COUT:   File "/home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb/__init__.py", line 257, in _sim_event
2020-05-26T17:36:56.5138049Z # COUT:     scheduler.finish_scheduler(SimFailure(msg))
2020-05-26T17:36:56.5205312Z # COUT:   File "/home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb/scheduler.py", line 826, in finish_scheduler
2020-05-26T17:36:56.5227447Z # COUT:     self._test.abort(exc)
2020-05-26T17:36:56.5305215Z # COUT:   File "/home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb/decorators.py", line 281, in abort
2020-05-26T17:36:56.5330567Z # COUT:     cocotb.scheduler.unschedule(self)
2020-05-26T17:36:56.5353890Z # COUT:   File "/home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb/scheduler.py", line 493, in unschedule
2020-05-26T17:36:56.5374269Z # COUT:     self.cleanup()
2020-05-26T17:36:56.5473880Z # COUT:   File "/home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb/scheduler.py", line 846, in cleanup
2020-05-26T17:36:56.5502830Z # COUT:     raise Exception("Cleanup() called outside of the main thread")
2020-05-26T17:36:56.5520793Z # COUT: Exception: Cleanup() called outside of the main thread
2020-05-26T17:36:56.5561367Z # COUT:      0.00ns ERROR    cocotb.gpi                                gpi_embed.cpp:349  in embed_sim_event                 Passing event to upper layer failed
2020-05-26T17:36:56.5662114Z # VSIM: Simulation has finished.
2020-05-26T17:36:56.6479423Z ERROR: results.xml was not written by the simulation!
2020-05-26T17:36:56.6513414Z /home/az_devops_agent/agent/_work/1/s/.tox/py3/lib/python3.6/site-packages/cocotb/share/makefiles/simulators/Makefile.riviera:146: recipe for target 'results.xml' failed
2020-05-26T17:36:56.6544788Z make[4]: *** [results.xml] Error 1
```

**Comment by themperek** [comment]
Duplicate #1859
