### ISSUE TITLE
Clang compilation broken

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2081]
When compiling with clang (`CXX=clang++ pip install .`) the compilation succeeds, but running yields the following traceback.
```
Traceback (most recent call last):
  File "/home/kaleb/miniconda3/bin/cocotb-config", line 5, in <module>
    from cocotb.config import main
  File "/home/kaleb/miniconda3/lib/python3.7/site-packages/cocotb/__init__.py", line 42, in <module>
    import cocotb.handle
  File "/home/kaleb/miniconda3/lib/python3.7/site-packages/cocotb/handle.py", line 36, in <module>
    from cocotb import simulator
ImportError: dynamic module does not define module export function (PyInit_simulator)
```
Using clang 10 on Ubuntu 20.04. Was likely introduced in #1796.

**Comment by ktbarrett** [comment]
Scratch that, I was being dumb. Should have also specified `CC=clang`. I guess I figured it should work even using gcc to link? Oh well...
