### ISSUE TITLE
Error when installing dev version

### ISSUE THREAD

**Issue by aignacio** [cocotb/cocotb#2356]
Hi,
I'm trying to install the development version with the following command:
```shell
pip3 install https://github.com/cocotb/cocotb/archive/master.zip
```
But I'm seeing the following error:
```shell
Collecting https://github.com/cocotb/cocotb/archive/master.zip
  Using cached https://github.com/cocotb/cocotb/archive/master.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/tmpq2mbofla
         cwd: /private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-req-build-y9pse3n_
    Complete output (37 lines):
    Modelsim/Questa executable (vdbg) executable not found. No FLI interface will be available.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 84, in <module>
        setup(
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 432, in __init__
        _Distribution.__init__(self, {
      File "/usr/local/Cellar/python@3.9/3.9.1_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 708, in finalize_options
        ep(self)
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools_scm/integration.py", line 26, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-build-env-p_2lwuut/overlay/lib/python3.9/site-packages/setuptools_scm/__init__.py", line 134, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/private/var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/pip-req-build-y9pse3n_'.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/lf/r2c_gptd3bs56lcv9f_bb59m0000gn/T/tmpq2mbofla Check the logs for full command output
```

I'm sorry if it's stupid question but maybe someone already faced that issue...I need to get the latest bc of the fat feature for Verilator builds.
Plataform: MacOS BigSur
Python: 3.8.2

**Comment by ktbarrett** [comment]
I noticed this the other day as well. Probably should have pursued the issue further before you ran into it. Instead of installing using `master.zip`, use pip's built in git functionality to install the development version.

```
python -m pip install git+https://github.com/cocotb/cocotb@master
```

I will update the docs to reflect this change and see about removing the zip file from PyPI.
