### ISSUE TITLE
[Tracking] Support installing to msys2 environment 

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2378]
After installing all of the prerequisite packages:
* python
* python-pip
* gcc
* make
* git

I cloned the sources locally, navigate to the project root, and ran `pip install -e .`. 

<details><summary>The output.</summary>

```
kaleb@DESKTOP-2CHBMVI MSYS ~/cocotb
$ python -m pip install -e .
Obtaining file:///home/kaleb/cocotb
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: cocotb
  Running setup.py develop for cocotb
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kaleb/cocotb/setup.py'"'"'; __file__='"'"'/home/kaleb/cocotb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/kaleb/cocotb/
    Complete output (38 lines):
    Modelsim/Questa executable (vdbg) executable not found. No FLI interface will be available.
    running develop
    running egg_info
    creating cocotb.egg-info
    writing cocotb.egg-info/PKG-INFO
    writing dependency_links to cocotb.egg-info/dependency_links.txt
    writing entry points to cocotb.egg-info/entry_points.txt
    writing top-level names to cocotb.egg-info/top_level.txt
    writing manifest file 'cocotb.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'cocotb.egg-info/SOURCES.txt'
    running build_ext
    building 'cocotb/libs/libgpilog' extension
    creating build
    creating build/temp.msys-3.1.7-x86_64-3.8
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog/cocotb
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog/cocotb/share
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog/cocotb/share/lib
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog/cocotb/share/lib/gpi_log
    x86_64-pc-msys-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -DGPILOG_EXPORTS= -D__STDC_FORMAT_MACROS= -Icocotb/share/include -I/usr/include/python3.8 -c cocotb/share/lib/gpi_log/gpi_logging.cpp -o build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog/cocotb/share/lib/gpi_log/gpi_logging.o -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wcast-qual -Wwrite-strings -Wconversion -Wnon-virtual-dtor -Woverloaded-virtual -flto
    creating build/lib.msys-3.1.7-x86_64-3.8
    creating build/lib.msys-3.1.7-x86_64-3.8/cocotb
    creating build/lib.msys-3.1.7-x86_64-3.8/cocotb/libs
    /usr/bin/g++ -shared -Wl,--enable-auto-image-base -pipe -L. -pipe -L. build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog/cocotb/share/lib/gpi_log/gpi_logging.o -Lbuild/lib.msys-3.1.7-x86_64-3.8/cocotb/libs -Lbuild/lib.msys-3.1.7-x86_64-3.8/cocotb/libs -L/usr/lib/python3.8/config -L/usr/lib -lpython3.8 -o build/lib.msys-3.1.7-x86_64-3.8/cocotb/libs/libgpilog.so -flto -Wl,-rpath,$ORIGIN
    building 'cocotb/libs/libpygpilog' extension
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog/cocotb
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog/cocotb/share
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog/cocotb/share/lib
    creating build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog/cocotb/share/lib/py_gpi_log
    x86_64-pc-msys-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -march=x86-64 -mtune=generic -O2 -pipe -DPYGPILOG_EXPORTS= -D__STDC_FORMAT_MACROS= -Icocotb/share/include -I/usr/include/python3.8 -c cocotb/share/lib/py_gpi_log/py_gpi_logging.cpp -o build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog/cocotb/share/lib/py_gpi_log/py_gpi_logging.o -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wcast-qual -Wwrite-strings -Wconversion -Wnon-virtual-dtor -Woverloaded-virtual -flto
    /usr/bin/g++ -shared -Wl,--enable-auto-image-base -pipe -L. -pipe -L. build/temp.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog/cocotb/share/lib/py_gpi_log/py_gpi_logging.o -Lbuild/lib.msys-3.1.7-x86_64-3.8/cocotb/libs -Lbuild/lib.msys-3.1.7-x86_64-3.8/cocotb/libs -L/usr/lib/python3.8/config -L/usr/lib -lgpilog -lpython3.8 -o build/lib.msys-3.1.7-x86_64-3.8/cocotb/libs/libpygpilog.so -flto -Wl,-rpath,$ORIGIN
    /usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgpilog
    collect2: error: ld returned 1 exit status
    error: command '/usr/bin/g++' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python.exe -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/kaleb/cocotb/setup.py'"'"'; __file__='"'"'/home/kaleb/cocotb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
``` 
</details>

In `build/lib.msys-3.1.7-x86_64-3.8/cocotb/libs` exists `libgpilog.so`. I'm guessing it's simply an issue of extension.

The same issue of detecting a Unix environment is affecting find_libpython, once we get to that point. https://github.com/ktbarrett/find_libpython/issues/2

**Comment by ktbarrett** [comment]
Mingw64 environments are also not currently supported due to a bug with setuptools_scm. https://github.com/pypa/setuptools_scm/issues/415.

<detail><summary>Output</summary>

```
kaleb@DESKTOP-2CHBMVI MINGW64 ~/cocotb
$ pip install .
Processing c:/msys64/home/kaleb/cocotb
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: C:/msys64/mingw64/bin/python.exe C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel C:/Users/kaleb/AppData/Local/Temp/tmpybwwxz73
         cwd: C:/Users/kaleb/AppData/Local/Temp/pip-req-build-nzmldzir
    Complete output (43 lines):
    Modelsim/Questa executable (vdbg) executable not found. No FLI interface will be available.
    Traceback (most recent call last):
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
        main()
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 84, in <module>
        setup(
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:/msys64/mingw64/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
        _Distribution.__init__(self, {
      File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 708, in finalize_options
        ep(self)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 26, in version_keyword
        dist.metadata.version = _get_version(config)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
        version = _version_from_entrypoints(config) or _version_from_entrypoints(
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
        version = _call_entrypoint_fn(root, config, ep.load())
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
        return fn(root, config=config)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/git.py", line 97, in parse
        wd = GitWorkdir.from_potential_worktree(config.absolute_root)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/git.py", line 33, in from_potential_worktree
        if not samefile(real_wd, wd):
      File "C:/msys64/mingw64/lib/python3.8/genericpath.py", line 100, in samefile
        s1 = os.stat(f1)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: '/c/Users/kaleb/AppData/Local/Temp/pip-req-build-nzmldzir'
    ----------------------------------------
WARNING: Discarding file:///C://msys64/home/kaleb/cocotb. Command errored out with exit status 1: C:/msys64/mingw64/bin/python.exe C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel C:/Users/kaleb/AppData/Local/Temp/tmpybwwxz73 Check the logs for full command output.
ERROR: Command errored out with exit status 1: C:/msys64/mingw64/bin/python.exe C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel C:/Users/kaleb/AppData/Local/Temp/tmpybwwxz73 Check the logs for full command output.
```

</detail>

**Comment by ktbarrett** [comment]
Incorrect libpython found on mingw64: https://github.com/ktbarrett/find_libpython/issues/1

**Comment by ktbarrett** [comment]
msys2 environment is broken. We are no longer supporting this environment.
