### ISSUE TITLE
[Tracking] Support installing to mingw environments

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2379]
Mingw-w64 environments are also not currently supported due to a bug with setuptools_scm. https://github.com/pypa/setuptools_scm/issues/415.

<details><summary>Output</summary>

```
kaleb@DESKTOP-2CHBMVI MINGW64 ~/cocotb
$ pip install .
Processing c:/msys64/home/kaleb/cocotb
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: C:/msys64/mingw64/bin/python.exe C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel C:/Users/kaleb/AppData/Local/Temp/tmpybwwxz73
         cwd: C:/Users/kaleb/AppData/Local/Temp/pip-req-build-nzmldzir
    Complete output (43 lines):
    Modelsim/Questa executable (vdbg) executable not found. No FLI interface will be available.
    Traceback (most recent call last):
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
        main()
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 84, in <module>
        setup(
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:/msys64/mingw64/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
        _Distribution.__init__(self, {
      File "C:/msys64/mingw64/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 708, in finalize_options
        ep(self)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/integration.py", line 26, in version_keyword
        dist.metadata.version = _get_version(config)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 127, in _do_parse
        version = _version_from_entrypoints(config) or _version_from_entrypoints(
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
        version = _call_entrypoint_fn(root, config, ep.load())
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
        return fn(root, config=config)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/git.py", line 97, in parse
        wd = GitWorkdir.from_potential_worktree(config.absolute_root)
      File "C:/Users/kaleb/AppData/Local/Temp/pip-build-env-44g311mr/overlay/lib/python3.8/site-packages/setuptools_scm/git.py", line 33, in from_potential_worktree
        if not samefile(real_wd, wd):
      File "C:/msys64/mingw64/lib/python3.8/genericpath.py", line 100, in samefile
        s1 = os.stat(f1)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: '/c/Users/kaleb/AppData/Local/Temp/pip-req-build-nzmldzir'
    ----------------------------------------
WARNING: Discarding file:///C://msys64/home/kaleb/cocotb. Command errored out with exit status 1: C:/msys64/mingw64/bin/python.exe C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel C:/Users/kaleb/AppData/Local/Temp/tmpybwwxz73 Check the logs for full command output.
ERROR: Command errored out with exit status 1: C:/msys64/mingw64/bin/python.exe C:/msys64/mingw64/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel C:/Users/kaleb/AppData/Local/Temp/tmpybwwxz73 Check the logs for full command output.
```

</details>

The issue with setuptools_scm only affects installing from source. Installing from sdist (after setuptools_scm runs) works.

Incorrect libpython found on mingw-w64: ktbarrett/find_libpython#1.

**Comment by ktbarrett** [comment]
setuptools_scm has been removed and find_libpython has been updated to work with mingw-w32/64. Due to issues with mingw-w64's Python installation, installing cocotb into that environment requires using the `--no-build-isolation` flag.
