### ISSUE TITLE
Singleton objects give bad error message

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#2559]
Calling `RisingEdge` with multiple arguments errors, but gives an error that does not point "directly" to `RisingEdge`.
```python
            await First(RisingEdge(self.interface.ready, self.interface.valid))
```

Error:
```
                     Traceback (most recent call last):
                       File "/home/kaleb/dev/pyvertb/test/test_streaming_adder/test_fifo.py", line 128, in run
                         await First(RisingEdge(self.interface.ready, self.interface.valid))
                       File "/home/kaleb/dev/cocotb/cocotb/utils.py", line 476, in __call__
                         key = cls.__singleton_key__(*args, **kwargs)
                     TypeError: __singleton_key__() takes 2 positional arguments but 3 were given
```

This could be tidied up easily.

**Comment by ktbarrett** [comment]
`ParametrizedSingleton` is dead. This is no longer an issue.
