### ISSUE TITLE
Issue when installing in Red-Hat Linux

### ISSUE THREAD

**Issue by msattine** [cocotb/cocotb#2707]
Hi, Im facing issue installing cocotb in redhat linux. I think its something basic, Please help.

Below is the signature.

************************************************************************************************************
Collecting cocotb
  Downloading https://files.pythonhosted.org/packages/0e/9f/ed64f793aa2d9837d8b157ea62673966c01cf457620d854ea74e4896d43f/cocotb-1.5.2.tar.gz (579kB)
    100% |████████████████████████████████| 583kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    Modelsim/Questa executable (vdbg) executable not found. No FLI interface will be available.
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    No local packages or working download links found for setuptools_scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ysgjrgo1/cocotb/setup.py", line 138, in <module>
        "bus": ["cocotb_bus"]
      File "/pkg/qct/software/python/3.6.0/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr2/msattine/Instals/my_env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')
*********************************************************************************************************************************

**Comment by ktbarrett** [comment]
It's in the error message.

> Couldn't find index page for 'setuptools_scm' (maybe misspelled?)

setuptools_scm is a dependency and is available on PyPI. You need to install that first since it seems like it's failing to get it.
