### ISSUE TITLE
Problems when installing cocotb without internet

### ISSUE THREAD

**Issue by petertufvesson** [cocotb/cocotb#3049]
I need to install cocotb without internet connection.
So I grabbed the code as cocotb-master.zip from github and transferred it to my computer, then unpacked it

Now I try to build & install and both succeedes:
```
python3 setup.py build
sudo python3 setup.py install
```
But now it is not possible to run cocotb-config:

```
$ cocotb-config 
Traceback (most recent call last):
  File "/bin/cocotb-config", line 33, in <module>
    sys.exit(load_entry_point('cocotb==1.7.0.dev0', 'console_scripts', 'cocotb-config')())
  File "/bin/cocotb-config", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: cocotb
```

If I try to import cocotb from within the same directory as it was unpacked, I get this error:

```
$ python3 -c "import cocotb"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/emp137@intra.advenica.com/cocotb-master/cocotb/__init__.py", line 43, in <module>
    import cocotb.handle
  File "/home/emp137@intra.advenica.com/cocotb-master/cocotb/handle.py", line 39, in <module>
    from cocotb import simulator
ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (/home/emp137@intra.advenica.com/cocotb-master/cocotb/__init__.py)
```

When I try the same command outside of the installation directory, it cannot be found at all.
```
$ python3 -c "import cocotb"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cocotb'
```

I also tried to install the same cocotb-master.zip using pip but it seems pip tried to install "setuptools" from internet even though it is already installed in the system.
```
$ pip install ./cocotb-master.zip 
/home/xx/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/xx/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Processing ./cocotb-master.zip
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e9tb6zui/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38fce4fd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38fdb161f0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38fce0cdf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38fce0cfd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f38fce0cca0>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools (from versions: none)
  ERROR: No matching distribution found for setuptools
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-e9tb6zui/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Check the logs for full command output.
```

I am lost and would appreciate any help.

**Comment by petertufvesson** [comment]
Here are the currently installed versions of some tools:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
emp137@FPGATEST:~$ python --version
```

```
$ python3 --version
Python 3.8.10
```

```
make --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
