### ISSUE TITLE
**pyuvm** tests  fails when running cocotb 1.7.1

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#3104]
The **pyuvm** test suite now fails when running with cocotb 1.7.1:

```
  File "/Users/raysalemi/repos/github_pyuvm/.tox/py38-macos/lib/python3.8/site-packages/cocotb/__init__.py", line 233, in _initialise_testbench
    _initialise_testbench_(argv_)
  File "/Users/raysalemi/repos/github_pyuvm/.tox/py38-macos/lib/python3.8/site-packages/cocotb/__init__.py", line 316, in _initialise_testbench_
    regression_manager = RegressionManager.from_discovery(top)
  File "/Users/raysalemi/repos/github_pyuvm/.tox/py38-macos/lib/python3.8/site-packages/cocotb/regression.py", line 160, in from_discovery
    return cls(dut, tests)
  File "/Users/raysalemi/repos/github_pyuvm/.tox/py38-macos/lib/python3.8/site-packages/cocotb/regression.py", line 147, in __init__
    self._queue.sort(key=lambda test: (test.stage, test._id))
TypeError: '<' not supported between instances of 'int' and 'NoneType'
Traceback (most recent call last):
  File "/Users/raysalemi/repos/github_pyuvm/.tox/py38-macos/lib/python3.8/site-packages/cocotb/__init__.py", line 341, in _sim_event
    scheduler.log.error(msg)
AttributeError: 'NoneType' object has no attribute 'log
```

**Comment by raysalemi** [comment]
I've tracked this down to something inside of pyuvm.
