### ISSUE TITLE
CI: MSVC/Windows/conda tests are failing with "ImportError: DLL load failed while importing _sqlite3: The specified module could not be found."

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#3326]
Another version of https://github.com/cocotb/cocotb/issues/3166 and https://github.com/cocotb/cocotb/issues/3183. We somehow need to find a more sustainable solution to this mess, it's our only Windows test in CI.

```
2023-06-06T22:59:19.6260505Z nox > Running simulator-agnostic tests with pytest
2023-06-06T22:59:19.6265500Z nox > pytest -v --cov=cocotb --cov-branch --cov-report= -k 'not simulator_required'
2023-06-06T22:59:19.9500265Z Traceback (most recent call last):
2023-06-06T22:59:19.9500850Z   File "C:\Miniconda\lib\runpy.py", line 194, in _run_module_as_main
2023-06-06T22:59:19.9501647Z     return _run_code(code, main_globals, None,
2023-06-06T22:59:19.9502232Z   File "C:\Miniconda\lib\runpy.py", line 87, in _run_code
2023-06-06T22:59:19.9502615Z     exec(code, run_globals)
2023-06-06T22:59:19.9503082Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\Scripts\pytest.EXE\__main__.py", line 7, in <module>
2023-06-06T22:59:19.9503508Z     sys.exit(console_main())
2023-06-06T22:59:19.9504394Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\config\__init__.py", line 189, in console_main
2023-06-06T22:59:19.9504859Z     code = main()
2023-06-06T22:59:19.9505426Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\config\__init__.py", line 147, in main
2023-06-06T22:59:19.9505897Z     config = _prepareconfig(args, plugins)
2023-06-06T22:59:19.9506505Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\config\__init__.py", line 328, in _prepareconfig
2023-06-06T22:59:19.9507034Z     config = pluginmanager.hook.pytest_cmdline_parse(
2023-06-06T22:59:19.9507654Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
2023-06-06T22:59:19.9508166Z     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
2023-06-06T22:59:19.9508790Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
2023-06-06T22:59:19.9509310Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2023-06-06T22:59:19.9509916Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
2023-06-06T22:59:19.9510341Z     gen.send(outcome)
2023-06-06T22:59:19.9510916Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\helpconfig.py", line 103, in pytest_cmdline_parse
2023-06-06T22:59:19.9511401Z     config: Config = outcome.get_result()
2023-06-06T22:59:19.9511998Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pluggy\_result.py", line 60, in get_result
2023-06-06T22:59:19.9512449Z     raise ex[1].with_traceback(ex[2])
2023-06-06T22:59:19.9513007Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
2023-06-06T22:59:19.9513469Z     res = hook_impl.function(*args)
2023-06-06T22:59:19.9514082Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\config\__init__.py", line 1067, in pytest_cmdline_parse
2023-06-06T22:59:19.9514527Z     self.parse(args)
2023-06-06T22:59:19.9515083Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\config\__init__.py", line 1354, in parse
2023-06-06T22:59:19.9515553Z     self._preparse(args, addopts=addopts)
2023-06-06T22:59:19.9516140Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\config\__init__.py", line 1237, in _preparse
2023-06-06T22:59:19.9516661Z     self.pluginmanager.load_setuptools_entrypoints("pytest11")
2023-06-06T22:59:19.9518972Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pluggy\_manager.py", line 287, in load_setuptools_entrypoints
2023-06-06T22:59:19.9519699Z     plugin = ep.load()
2023-06-06T22:59:19.9520124Z   File "C:\Miniconda\lib\importlib\metadata.py", line 77, in load
2023-06-06T22:59:19.9520615Z     module = import_module(match.group('module'))
2023-06-06T22:59:19.9521062Z   File "C:\Miniconda\lib\importlib\__init__.py", line 127, in import_module
2023-06-06T22:59:19.9521579Z     return _bootstrap._gcd_import(name[level:], package, level)
2023-06-06T22:59:19.9522011Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2023-06-06T22:59:19.9522427Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2023-06-06T22:59:19.9522871Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2023-06-06T22:59:19.9523304Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2023-06-06T22:59:19.9523936Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\_pytest\assertion\rewrite.py", line 172, in exec_module
2023-06-06T22:59:19.9524539Z     exec(co, module.__dict__)
2023-06-06T22:59:19.9525105Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\pytest_cov\plugin.py", line 6, in <module>
2023-06-06T22:59:19.9525542Z     import coverage
2023-06-06T22:59:19.9526077Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\coverage\__init__.py", line 22, in <module>
2023-06-06T22:59:19.9526525Z     from coverage.control import (
2023-06-06T22:59:19.9527081Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\coverage\control.py", line 28, in <module>
2023-06-06T22:59:19.9527585Z     from coverage.collector import Collector, HAS_CTRACER
2023-06-06T22:59:19.9528194Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\coverage\collector.py", line 19, in <module>
2023-06-06T22:59:19.9528652Z     from coverage.data import CoverageData
2023-06-06T22:59:19.9529229Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\coverage\data.py", line 24, in <module>
2023-06-06T22:59:19.9529713Z     from coverage.sqldata import CoverageData
2023-06-06T22:59:19.9530276Z   File "D:\a\cocotb\cocotb\.nox\dev_test_nosim\lib\site-packages\coverage\sqldata.py", line 18, in <module>
2023-06-06T22:59:19.9530714Z     import sqlite3
2023-06-06T22:59:19.9531221Z   File "C:\Miniconda\lib\sqlite3\__init__.py", line 23, in <module>
2023-06-06T22:59:19.9531619Z     from sqlite3.dbapi2 import *
2023-06-06T22:59:19.9532013Z   File "C:\Miniconda\lib\sqlite3\dbapi2.py", line 27, in <module>
2023-06-06T22:59:19.9532393Z     from _sqlite3 import *
2023-06-06T22:59:19.9532830Z ImportError: DLL load failed while importing _sqlite3: The specified module could not be found.
2023-06-06T22:59:19.9789277Z nox > Command pytest -v --cov=cocotb --cov-branch --cov-report= -k 'not simulator_required' failed with exit code 1
2023-06-06T22:59:19.9789952Z nox > Session dev_test_nosim failed.
```

**Comment by ktbarrett** [comment]
One possible solution is to not use conda as an environment. We could build cocotb with MSVC, use the python.org installer and use only make from mingw? Or we could port all the tests to the Python runner and not need make anymore.
