### ISSUE TITLE
GHDL IndexError with in/out port arrays

### ISSUE THREAD

**Issue by franhervas99** [cocotb/cocotb#3546]
> cocotb version: 1.8.1
> OS: 22.04.1-Ubuntu
> simulator: GHDL 4.0.0-dev (tarball) [Dunoon edition]
> python: 3.10.12

Hello everyone,

I found that that matrix multiplier cocotb example does not work when you are running GHDL as simulator.  That is because of an error that occurs when you try to access input/output ports, when they are implemented as arrays.
Later I found that this is just handled  as an expected error, at the parameters of the `cocotb.test()` decorator:
```python
...
@cocotb.test(
    expect_error=IndexError
    if cocotb.simulator.is_running() and cocotb.SIM_NAME.lower().startswith("ghdl")
    else ()
)
async def multiply_test(dut):
    """Test multiplication of many matrices."""
...
```
When you comment the lines that handles the `IndexError`, the following error raises:
```python
     0.00ns WARNING  gpi                                Failed to find a handle at index 0 via any registered implementation
     0.00ns INFO     cocotb.regression                  multiply_test failed
                                                        Traceback (most recent call last):
                                                          File "/home/francisco/IFIC/cocotb_examples/matrix_multiplier/tests/test_matrix_multiplier.py", line 163, in multiply_test
                                                            dut.a_i.value = create_a(lambda x: 0)
                                                          File "/home/francisco/.local/lib/python3.10/site-packages/cocotb/handle.py", line 201, in __setattr__
                                                            return object.__setattr__(self, name, value)
                                                          File "/home/francisco/.local/lib/python3.10/site-packages/cocotb/handle.py", line 489, in value
                                                            self._set_value(value, cocotb.scheduler._schedule_write)
                                                          File "/home/francisco/.local/lib/python3.10/site-packages/cocotb/handle.py", line 706, in _set_value
                                                            self[self_idx]._set_value(value[val_idx], call_sim)
                                                          File "/home/francisco/.local/lib/python3.10/site-packages/cocotb/handle.py", line 652, in __getitem__
                                                            raise IndexError(
                                                        IndexError: a_i(GPI_ARRAY) contains no object at index 0

```

I just realized on that because I'm trying to access to an in/out port array on my design.

- Is this something related to GHDL or to cocotb?
- Is there any way to solve it?

Any help would be appreciated,
Thank you in advance!

**Comment by marlonjames** [comment]
This is a known GHDL issue. See #2603
