### ISSUE TITLE
Verifying SystemC code with OSCI Simulator

### ISSUE THREAD

**Issue by jahagirdar** [cocotb/cocotb#731]
Is it possible to use cocotb to verify systemc code using the opensource OSCI simulator?

**Comment by cmarqu** [comment]
I highly doubt it, since OSCI has neither VPI, VHPI, nor FLI which cocotb uses internally.

**Comment by jahagirdar** [comment]
How easy/difficult is it to bolt on the subset of VPI/VHPI interface required by cocoTB to OSCI?
Can we for example, modify the  interface from iverilog or ghdl and instantiate it under sc_main()?

**Comment by wallento** [comment]
Hi, I am planning to look into it. It sounds reasonable to do it. Cheers

**Comment by ktbarrett** [comment]
We'll add support for OSCI when it supports us. Open a new issue if there have been developments and this is now possible.

**Comment by cmarqu** [comment]
Thanks to the work of @mballance and @bhavayarora-bosch, https://github.com/fvutils/scvpi can now be used to do this:

> SCVPI is a VPI-compatible interface for SystemC that enables cocotb and cocotb-based frameworks such as PyUVM to run on SystemC models.

**Comment by ktbarrett** [comment]
@cmarqu Is there anything we need to do here to better support that integration? Do we need a scvpi simulator, or is that handled by the scvpi package?

**Comment by cmarqu** [comment]
SCVPI needs SystemC installed which is available as a system package on Debian/Ubuntu: 
https://github.com/fvutils/scvpi/blob/34fa5e46841d31aaeed731edd39f7aedf09cbf3b/.github/workflows/ci.yaml#L36
For other systems, SystemC would have to be compiled separately.

The rest runs like this (taken from the GitHub Action run of the merged PR in the scvpi repo):

```

make: Entering directory '/home/runner/work/scvpi/scvpi/examples/basic'
=== SystemC Configuration ===
SYSTEMC: /usr
SYSTEMC_LIB_LINUX64: /usr/lib-linux64
SYSTEMC_LIB64: /usr/lib64

=== cocotb Configuration ===
COCOTB_PREFIX: 
COCOTB_LIBPYTHON: /usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0
COCOTB_LIBPYTHON_DIR: /usr/lib/x86_64-linux-gnu/
COCOTB_PYTHON_BIN: /home/runner/work/scvpi/scvpi/.venv/bin/python3

=== VPI Libraries ===
COCOTB_VPI_VERILATOR: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_verilator.so
COCOTB_VPI_QUESTA: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_modelsim.so
COCOTB_VPI_XCELIUM: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_ius.so
COCOTB_VPI_ICARUS: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_icarus.vpl
make: Leaving directory '/home/runner/work/scvpi/scvpi/examples/basic'
make: Entering directory '/home/runner/work/scvpi/scvpi/examples/basic'
g++ -I/usr/include -I. -I../../src -export-dynamic ../../src/scvpi.cpp test.cpp -o test -L/usr/lib-linux64 -L/usr/lib64 -ldl -lsystemc
Running cocotb test with Icarus...

        SystemC 2.3.4-Accellera --- Apr 22 2024 14:54:19
        Copyright (c) 1996-2022 by all Contributors,
        ALL RIGHTS RESERVED
Load VPI: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_icarus.vpl
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:93   in _embed_init_python              Using Python 3.12.4 interpreter at /home/runner/work/scvpi/scvpi/.venv/bin/python3
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:79   in gpi_print_registered_impl       VPI registered
     0.00ns INFO     cocotb                             Running on SCVPI (SystemC) version SystemC
     0.00ns WARNING  gpi                                vpi_iterate returned NULL for type vpiInstance for object NULL
     0.00ns INFO     cocotb                             Seeding Python random module with 1771371629
     0.00ns INFO     cocotb                             Initialized cocotb v2.0.1 from /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb
Hello from TB
     0.00ns INFO     cocotb                             Running tests
     0.00ns INFO     cocotb.regression                  running tb.my_test (1/1)
my_test: HierarchyObject(abc)
  h: 
--> wait 1
my_task
<-- wait 1
--> wait 2
<-- wait 2
--> wait 3
<-- wait 3
--> wait 4
<-- wait 4
   122.00ns INFO     cocotb.regression                  tb.my_test passed
   122.00ns INFO     cocotb.regression                  **************************************************************************************
                                                        ** TEST                          STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
                                                        **************************************************************************************
                                                        ** tb.my_test                     PASS         122.00           0.00     196961.16  **
                                                        **************************************************************************************
                                                        ** TESTS=1 PASS=1 FAIL=0 SKIP=0                122.00           0.00      68354.94  **
                                                        **************************************************************************************
                                                        
top::end_of_elaboration sc_argc=3

Info: /OSCI/SystemC: Simulation stopped by user.
make: Leaving directory '/home/runner/work/scvpi/scvpi/examples/basic'
make: Entering directory '/home/runner/work/scvpi/scvpi/examples/adder'
SYSTEMC=/usr
COCOTB_PYTHON_BIN=/home/runner/work/scvpi/scvpi/.venv/bin/python3
COCOTB_VPI_ICARUS=/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_icarus.vpl
make: Leaving directory '/home/runner/work/scvpi/scvpi/examples/adder'
make: Entering directory '/home/runner/work/scvpi/scvpi/examples/adder'
g++ -I/usr/include -I. -I../../src -export-dynamic ../../src/scvpi.cpp adder.cpp -o test -L/usr/lib-linux64 -ldl -lsystemc
Running cocotb adder test (Icarus)...

        SystemC 2.3.4-Accellera --- Apr 22 2024 14:54:19
        Copyright (c) 1996-2022 by all Contributors,
        ALL RIGHTS RESERVED
Load VPI: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_icarus.vpl
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:93   in _embed_init_python              Using Python 3.12.4 interpreter at /home/runner/work/scvpi/scvpi/.venv/bin/python3
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:79   in gpi_print_registered_impl       VPI registered
     0.00ns INFO     cocotb                             Running on SCVPI (SystemC) version SystemC
     0.00ns WARNING  gpi                                vpi_iterate returned NULL for type vpiInstance for object NULL
     0.00ns INFO     cocotb                             Seeding Python random module with 1771371632
     0.00ns INFO     cocotb                             Initialized cocotb v2.0.1 from /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb
     0.00ns INFO     cocotb                             Running tests
     0.00ns INFO     cocotb.regression                  running tb.test_adder_vectors (1/3)
     7.00ns INFO     cocotb.regression                  tb.test_adder_vectors passed
     7.00ns INFO     cocotb.regression                  running tb.test_adder_random (2/3)
    38.00ns INFO     cocotb.regression                  tb.test_adder_random passed
    38.00ns INFO     cocotb.regression                  running tb.test_adder_error_demo (3/3)
                                                            Intentional mismatch demo (does not fail CI)
    40.00ns WARNING  test                               [DEMO] Intentional mismatch: a=10 b=20 got=30 expected=999
    40.00ns INFO     cocotb.regression                  tb.test_adder_error_demo passed
    40.00ns INFO     cocotb.regression                  **************************************************************************************
                                                        ** TEST                          STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
                                                        **************************************************************************************
                                                        ** tb.test_adder_vectors          PASS           7.00           0.00       6090.05  **
                                                        ** tb.test_adder_random           PASS          30.00           0.00       9022.60  **
                                                        ** tb.test_adder_error_demo       PASS           1.00           0.00       3768.47  **
                                                        **************************************************************************************
                                                        ** TESTS=3 PASS=3 FAIL=0 SKIP=0                 40.00           0.01       5623.15  **
                                                        **************************************************************************************
                                                        

Info: /OSCI/SystemC: Simulation stopped by user.
make: Leaving directory '/home/runner/work/scvpi/scvpi/examples/adder'
make: Entering directory '/home/runner/work/scvpi/scvpi/examples/TinyALU_SystemC'
=== TinyALU SystemC Configuration ===
SYSTEMC: /usr
CXX: g++
SCVPI_SRC: ../../src

=== Cocotb Configuration ===
COCOTB_PYTHON_BIN: /home/runner/work/scvpi/scvpi/.venv/bin/python3
COCOTB_LIBPYTHON: /usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0
COCOTB_VPI_ICARUS: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_icarus.vpl
make: Leaving directory '/home/runner/work/scvpi/scvpi/examples/TinyALU_SystemC'
make: Entering directory '/home/runner/work/scvpi/scvpi/examples/TinyALU_SystemC'
g++ -I/usr/include -I./hdl -I../../src -export-dynamic ../../src/scvpi.cpp hdl/main.cpp -o test -L/usr/lib-linux64 -ldl -lsystemc

        SystemC 2.3.4-Accellera --- Apr 22 2024 14:54:19
        Copyright (c) 1996-2022 by all Contributors,
        ALL RIGHTS RESERVED
Load VPI: /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb/libs/libcocotbvpi_icarus.vpl
     -.--ns INFO     gpi                                ..mbed/gpi_embed.cpp:93   in _embed_init_python              Using Python 3.12.4 interpreter at /home/runner/work/scvpi/scvpi/.venv/bin/python3
     -.--ns INFO     gpi                                ../gpi/GpiCommon.cpp:79   in gpi_print_registered_impl       VPI registered
     0.00ns INFO     cocotb                             Running on SCVPI (SystemC) version SystemC
     0.00ns WARNING  gpi                                vpi_iterate returned NULL for type vpiInstance for object NULL
     0.00ns INFO     cocotb                             Seeding Python random module with 1771371635
     0.00ns INFO     cocotb                             Initialized cocotb v2.0.1 from /home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/cocotb
     0.00ns INFO     cocotb                             Running tests
     0.00ns INFO     cocotb.regression                  running testbench.AluTest (1/4)
                                                            Test ALU with random and max values
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0x10 ADD 0x8b = 0x009b
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0x91 AND 0x4e = 0x0000
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xb7 XOR 0x6b = 0x00dc
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xe0 MUL 0x00 = 0x0000
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff ADD 0xff = 0x01fe
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff AND 0xff = 0x00ff
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff XOR 0xff = 0x0000
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff MUL 0xff = 0xfe01
 49000.00ns INFO     ..inyALU_SystemC/testbench.py(185) [uvm_test_top.env.coverage]: Covered all operations
 49000.00ns INFO     cocotb.regression                  testbench.AluTest passed
 49000.00ns INFO     cocotb.regression                  running testbench.ParallelTest (2/4)
                                                            Test ALU random and max forked
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0x1f ADD 0x53 = 0x0072
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff ADD 0xff = 0x01fe
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0x35 AND 0xb0 = 0x0030
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff AND 0xff = 0x00ff
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xa7 XOR 0x9d = 0x003a
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff XOR 0xff = 0x0000
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xb6 MUL 0xda = 0x9afc
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(218) [uvm_test_top.env.scoreboard]: PASSED: 0xff MUL 0xff = 0xfe01
 98001.00ns INFO     ..inyALU_SystemC/testbench.py(185) [uvm_test_top.env.coverage]: Covered all operations
 98001.00ns INFO     cocotb.regression                  testbench.ParallelTest passed
 98001.00ns INFO     cocotb.regression                  running testbench.FibonacciTest (3/4)
                                                            Run Fibonacci program
131002.00ns INFO     ..inyALU_SystemC/testbench.py(139) []: Fibonacci Sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21]
131002.00ns INFO     cocotb.regression                  testbench.FibonacciTest passed
131002.00ns INFO     cocotb.regression                  running testbench.AluTestErrors (4/4)
                                                            Test ALU with errors on all operations
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0x5a ADD 0x80 = 0x00da expected 0x00db
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0xd8 AND 0x8a = 0x0088 expected 0x0089
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0xf6 XOR 0xcc = 0x003a expected 0x003b
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0x29 MUL 0xb7 = 0x1d4f expected 0x1d50
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0xff ADD 0xff = 0x01fe expected 0x01ff
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0xff AND 0xff = 0x00ff expected 0x0100
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0xff XOR 0xff = 0x0000 expected 0x0001
180003.00ns ERROR    ..inyALU_SystemC/testbench.py(222) [uvm_test_top.env.scoreboard]: FAILED: 0xff MUL 0xff = 0xfe01 expected 0xfe02
180003.00ns WARNING  ..Test AluTestErrors.AluTestErrors assert False
                                                        Traceback (most recent call last):
                                                          File "/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/pyuvm/extension_classes.py", line 42, in test_obj
                                                            await uvm_root().run_test(
                                                          File "/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/pyuvm/s13_uvm_component.py", line 480, in run_test
                                                            self.running_phase.traverse(self.uvm_test_top)
                                                          File "/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/pyuvm/s09_phasing.py", line 65, in traverse
                                                            cls.traverse(child)
                                                          File "/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/pyuvm/s09_phasing.py", line 65, in traverse
                                                            cls.traverse(child)
                                                          File "/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/pyuvm/s09_phasing.py", line 63, in traverse
                                                            cls.execute(comp)  # first we execute this node then its children
                                                            ^^^^^^^^^^^^^^^^^
                                                          File "/home/runner/work/scvpi/scvpi/.venv/lib/python3.12/site-packages/pyuvm/s09_phasing.py", line 44, in execute
                                                            method()
                                                          File "/home/runner/work/scvpi/scvpi/examples/TinyALU_SystemC/testbench.py", line 228, in check_phase
                                                            assert passed
                                                        AssertionError: assert False
180003.00ns INFO     cocotb.regression                  testbench.AluTestErrors passed: failed as expected
180003.00ns INFO     cocotb.regression                  **************************************************************************************
                                                        ** TEST                          STATUS  SIM TIME (ns)  REAL TIME (s)  RATIO (ns/s) **
                                                        **************************************************************************************
                                                        ** testbench.AluTest              PASS       49000.00           0.01    3361205.27  **
                                                        ** testbench.ParallelTest         PASS       49000.00           0.02    3263427.85  **
                                                        ** testbench.FibonacciTest        PASS       33000.00           0.01    2705103.52  **
                                                        ** testbench.AluTestErrors        PASS       49000.00           0.02    3235836.13  **
                                                        **************************************************************************************
                                                        ** TESTS=4 PASS=4 FAIL=0 SKIP=0             180003.00           0.08    2246030.12  **
                                                        **************************************************************************************
                                                        

Info: /OSCI/SystemC: Simulation stopped by user.
make: Leaving directory '/home/runner/work/scvpi/scvpi/examples/TinyALU_SystemC'
```
