### ISSUE TITLE
Co-simulation encounters  No context available error

### ISSUE THREAD

**Issue by kleon1024** [cocotb/cocotb#891]
Hi,
   I'm trying to build a simulation environment following the tutorial: Driver Cosimulation.
  
   I write a C program with python API (like tensorflow) and link to a driver simulation shared library (libdriver.so). 

  Cocotb binds the @cocotb.function with APIs in libdriverso correctly, and calls yield cocotb.external. But encounters No context available when calling PyObject_CallObject().

Thanks.

Command line: sim_build/simv +define+COCOTB_SIM=1

--- Stack trace follows:
```
Dumping VCS Annotated Stack:
#0  0x00007ffff0aaae09 in waitpid () from /usr/lib64/libc.so.6
#1  0x00007ffff0a2dcc2 in do_system () from /usr/lib64/libc.so.6
#2  0x00007ffff0a2e071 in system () from /usr/lib64/libc.so.6
#3  0x00007ffff70c20ab in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313e639d2928478c79b3f673f99203bcf8be64600612100082236bffb2007f1e0ef9 () from /home/software/Synopsys/vcs2017.3/linux64/lib/liberrorinf.so
#4  0x00007ffff70c3746 in SNPSle_10ee25eff68cd8461c9146fa1d0b35e87067f3c8015b313efba706aab251478fa49e66610e453774633a6c152e7ef778f2202cda681f3d4e () from /home/software/Synopsys/vcs2017.3/linux64/lib/liberrorinf.so
#5  0x00007ffff70bcb85 in SNPSle_d35ca1ff70d465c2b9b1a72eee90a506fdd009d3de3db1de () from /home/software/Synopsys/vcs2017.3/linux64/lib/liberrorinf.so
#6  0x00007ffff4511028 in SNPSle_64133461705005bb725549e2e6fa1b3f () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#7  0x00007ffff438015e in SNPSle_82244d58c54c18c70d63edc9becab634 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#9  0x00007fffea641a4a in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#10 0x00007fffea6d38f7 in PyEval_CallObjectWithKeywords () from /usr/lib64/libpython2.7.so.1.0

Calling.. wrapped C API & libdriver.so's API.

#23 0x00007fffea6dacf0 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#24 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#25 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#26 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#27 0x00007fffea666978 in ?? () from /usr/lib64/libpython2.7.so.1.0
#28 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#29 0x00007fffea6d56fd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#30 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#31 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#32 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#33 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#34 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#35 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#36 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#37 0x00007fffea666a6d in ?? () from /usr/lib64/libpython2.7.so.1.0
#38 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#39 0x00007fffea6d56fd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#40 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#41 0x00007fffea666a6d in ?? () from /usr/lib64/libpython2.7.so.1.0
#42 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#43 0x00007fffea6d56fd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#44 0x00007fffea6da6bd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#45 0x00007fffea6da6bd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#46 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#47 0x00007fffea666978 in ?? () from /usr/lib64/libpython2.7.so.1.0
#48 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#49 0x00007fffea650a55 in ?? () from /usr/lib64/libpython2.7.so.1.0
#50 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#51 0x00007fffea6d38f7 in PyEval_CallObjectWithKeywords () from /usr/lib64/libpython2.7.so.1.0
#52 0x00007fffea70b822 in ?? () from /usr/lib64/libpython2.7.so.1.0
#53 0x00007ffff13c0e25 in start_thread () from /usr/lib64/libpthread.so.0
#54 0x00007ffff0ae434d in clone () from /usr/lib64/libc.so.6
#0  0x00007ffff13c6a0b in do_futex_wait.constprop () from /usr/lib64/libpthread.so.0
#1  0x00007ffff13c6a9f in __new_sem_wait_slow.constprop.0 () from /usr/lib64/libpthread.so.0
#2  0x00007ffff13c6b3b in sem_wait@@GLIBC_2.2.5 () from /usr/lib64/libpthread.so.0
#3  0x00007fffea707735 in PyThread_acquire_lock () from /usr/lib64/libpython2.7.so.1.0
#4  0x00007fffea70b422 in ?? () from /usr/lib64/libpython2.7.so.1.0
#5  0x00007fffea6dacf0 in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#6  0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#7  0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#8  0x00007fffea6da6bd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#9  0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#10 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#11 0x00007fffea6da6bd in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#12 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#13 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#14 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#15 0x00007fffea6da53c in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
#16 0x00007fffea6dd03d in PyEval_EvalCodeEx () from /usr/lib64/libpython2.7.so.1.0
#17 0x00007fffea666978 in ?? () from /usr/lib64/libpython2.7.so.1.0
#18 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#19 0x00007fffea650a55 in ?? () from /usr/lib64/libpython2.7.so.1.0
#20 0x00007fffea641a63 in PyObject_Call () from /usr/lib64/libpython2.7.so.1.0
#21 0x00007fffe6f10936 in handle_gpi_callback (user_data=0xe18ab0) at simulatormodule.c:141
#22 0x00007fffeabd164d in GpiValueCbHdl::run_callback (this=0x14ad4d0) at GpiCbHdl.cpp:201
#23 0x00007fffeaff459e in handle_vpi_callback (cb_data=0x7fffffffbdc0) at VpiImpl.cpp:543
#24 0x00007ffff372aa77 in SNPSle_fb3a9652f2e3b68b5447922ab4ebc9f0782f457b36908be8fb285a2edba0a39dc136cc210a7c05e3bbcbcf643cdb038b01c00ec935c2811c3ad39af85d404bef () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#25 0x00007ffff372c1f9 in SNPSle_fb3a9652f2e3b68b5447922ab4ebc9f0aa637b2e51f30719b69c87c3ddda24ea5213c91730b4d3df2a941dba5c7763b7 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#26 0x00007ffff3728ddc in SNPSle_63db351721528760c5d54268916bce08cc310eab90ba18fe () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#27 0x00007ffff3e1e79c in SNPSle_63db3517215287605a99b3095c6f394fc2db1dbeb96dd5fcf8612963f1a166220f386a95694ce299 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#28 0x00007ffff3e2abed in SNPSle_bcaf03cfbe6cb6298cb79b8f0b76f6f7 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#29 0x00007ffff3e2b68e in SNPSle_35d1920863e16fc45674e6a98588befaa45d05033a75bec7ea76cb8a82b210686a9ce7bc64560755 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#30 0x00007ffff47c1f66 in SNPSle_caf6869f8e03a5db6541c65a8ff4abb8a8a66fdc7ec97e7e1ddbd714cc1f3081 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#31 0x000000000040642a in hs_0_M_1_21__simv_daidir ()
#32 0x00000000004065e8 in hs_0_M_1_11__simv_daidir ()
#33 0x00007ffff47beaac in SNPSle_9bd56f6f8c562fdfca664c84016d31734f0d0a7d0fba7af4 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#34 0x00007ffff47beeb5 in SNPSle_9bd56f6f8c562fdfc2f0563e6b398487 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#35 0x00007ffff47c3c65 in SNPSle_5f20c58f0105ed4a96b20c3d9086200f () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#36 0x00007ffff3eac96d in SNPSle_e8f7c68db9054d35063471343b08b764 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#37 0x00007ffff3eadaf9 in SNPSle_0741589259cb66ec0c4d44ae49b1e1f0 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#38 0x00007ffff371aed7 in SNPSle_eeb6993e4e46a907a4c528c7fc1ae84a8290b3f004ada8b9519340344bda2389 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#39 0x00007ffff371c0ec in SNPSle_009a556280812a37dba5239c1809e8d10399ce57f76bcd9169a2a07b5e1db2660cbc80167ab9e49f7b4028754ce53f927a0d500054bb5cf5 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#40 0x00007ffff371d429 in SNPSle_136ff4087e5c3c2202aa948583e38564bcfc388ae6bf46da () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#41 0x00007ffff3eac5fe in SNPSle_136ff4087e5c3c2202aa948583e38564a211dec83da54635 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#42 0x00007ffff44cded0 in SNPSle_63c7abb936d47b07d29d61775f9dbe8c () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#43 0x00007ffff452597f in SNPSle_490598bfebcc8e81efcf3d1815066cc9 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#44 0x00007ffff4539428 in SNPSle_490598bfebcc8e81 () from /home/software/Synopsys/vcs2017.3/linux64/lib/libvcsnew.so
#45 0x00000000004061cb in main ()
No context available
```

**Comment by imphil** [comment]
@KleonGit thanks for reporting this issue. Unfortunately, I cannot see anything suspicious in the stack trace and we need a code example to be able to reproduce this.

Can you produce a small, self-contained test case that shows this problem? For example by using/extending the cosim example?
